// This component was generated by AI - Claude 3.5 Sonnet (Preview)
'use client';

import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Pagination, A11y } from 'swiper/modules';
import ImageWithFallback from './ImageWithFallback';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

interface ImageCarouselProps {
  images: string[];
  alt: string;
  height?: 'h-64' | 'h-96';
}

export default function ImageCarousel({ images, alt, height = 'h-96' }: ImageCarouselProps) {
  // Add debug logging
  console.log('ImageCarousel received images:', images);

  // Ensure images is always an array and contains valid URLs
  const validImages = Array.isArray(images) ? images.filter(url => url && typeof url === 'string') : [];

  // Don't render carousel if no valid images
  if (validImages.length === 0) {
    return (
      <div className={`${height} bg-gray-200 dark:bg-gray-700 flex items-center justify-center`}>
        <span className="text-gray-400">No images available</span>
      </div>
    );
  }

  return (
    <Swiper
      modules={[Navigation, Pagination, A11y]}
      spaceBetween={0}
      slidesPerView={1}
      navigation
      pagination={{ clickable: true }}
      className={height}
    >
      {validImages.map((url, index) => (
        <SwiperSlide key={`${url}-${index}`}>
          <ImageWithFallback
            src={url}
            alt={`${alt} - Image ${index + 1}`}
            className="w-full h-full object-cover"
          />
        </SwiperSlide>
      ))}
    </Swiper>
  );
}
