// This component was generated by AI - Claude 3.5 Sonnet (Preview)
'use client';

import { useRef } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Pagination, A11y } from 'swiper/modules';
import type { Swiper as SwiperType } from 'swiper';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

interface ImageModalProps {
  src: string;
  images: string[];
  alt: string;
  onClose: () => void;
  initialSlide?: number;
}

export default function ImageModal({ src, images, alt, onClose, initialSlide = 0 }: ImageModalProps) {
  const swiperRef = useRef<SwiperType | null>(null);

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-90 z-50 flex items-center justify-center p-8"
      onClick={onClose}
    >
      <div className="relative max-w-6xl w-full max-h-[85vh] modal-animation" onClick={e => e.stopPropagation()}>
        {/* Close button - Static styling */}
        <button
          onClick={onClose}
          className="absolute -top-4 -right-4 bg-black text-white 
            w-10 h-10 rounded-full flex items-center justify-center text-xl z-50 shadow-lg"
          aria-label="Close modal"
        >
          ✕
        </button>
        
        {/* Enhanced Navigation Arrows */}
        <button 
          onClick={() => swiperRef.current?.slidePrev()}
          className="absolute left-4 top-1/2 transform -translate-y-1/2 z-20 
            text-white hover:text-white bg-black/70 hover:bg-black/90 
            w-12 h-12 rounded-full transition-all duration-200
            flex items-center justify-center text-3xl
            shadow-lg backdrop-blur-sm
            hover:scale-110 hover:w-14 hover:h-14"
          aria-label="Previous image"
        >
          ‹
        </button>
        <button 
          onClick={() => swiperRef.current?.slideNext()}
          className="absolute right-4 top-1/2 transform -translate-y-1/2 z-20 
            text-white hover:text-white bg-black/70 hover:bg-black/90 
            w-12 h-12 rounded-full transition-all duration-200
            flex items-center justify-center text-3xl
            shadow-lg backdrop-blur-sm
            hover:scale-110 hover:w-14 hover:h-14"
          aria-label="Next image"
        >
          ›
        </button>

        <Swiper
          modules={[Navigation, Pagination, A11y]}
          spaceBetween={0}
          slidesPerView={1}
          loop={true}
          initialSlide={initialSlide}
          pagination={{
            clickable: true,
            type: 'bullets',
            renderBullet: (index, className) => {
              return `<span class="${className} w-2.5 h-2.5 bg-white/50 hover:bg-white/75 transition-all"></span>`;
            },
          }}
          onBeforeInit={(swiper) => {
            swiperRef.current = swiper;
          }}
          className="w-full aspect-[16/9]"
        >
          {images.map((image, index) => (
            <SwiperSlide key={`modal-slide-${index}`}>
              <img
                src={image}
                alt={`${alt} - Image ${index + 1}`}
                className="absolute inset-0 w-full h-full object-contain rounded-lg"
              />
            </SwiperSlide>
          ))}
        </Swiper>
      </div>
    </div>
  );
}